### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by cyource** [the-twee/html5-pong#1]
Hi there Shreyas Pandit/Harrison Wells/The-Twee,

Lol the Harrison Wells bit was a Flash reference.
I believe that the name of this project should be more exciting - like Pongify, HyperPong, PanditPong (what?), XtremePong - basically anything not html5-pong. 

-cyource

**Comment by cyource** [comment]
Awesome fireworks btw

**Comment by the-twee** [comment]
Ok... I'll think about the name.
Thanks
Did you run the fireworks on Windows? They seem to freak out on Windows
... run them on linux

**Comment by the-twee** [comment]
You don't need to add this as an issue...

**Comment by cyource** [comment]
Sorry lol I didn't have any other way of contacting you

**Comment by cyource** [comment]
I don't use linux. Am thinking of, however, in the future.

**Comment by the-twee** [comment]
Ok... but they seem to act really wierd. They look great on Linux but not
on Windows... I'm not sure why though

**Comment by cyource** [comment]
Still cool on Windows. Faster = better in my book.

**Comment by cyource** [comment]
Ah, they are a bit buggy. Sorry for spamming the /issues of this repo with this.

**Comment by the-twee** [comment]
Yes please don't....

**Comment by cyource** [comment]
I heard you're good with HTML/CSS. Do you have any experience with Liquid and Jekyll, because I need help with improving my blog? Again, apologies for... "spamming" this closed issue. Gitter later?

**Comment by cyource** [comment]
Nevermind, fixed it
